### ISSUE TITLE
Error when adding communication devices to robots

### ISSUE THREAD

**Issue by aldoteran** [smarc-project/smarc_stonefish_sims#26]
Hola!

Been working with both SAM and LoLo in the simulator and I've encountered an error when fitting either of the robots with a communication device. I get the following error (from the log file):
`[ERROR] Specs of communication device 'sam/USBL' not properly defined!`
`[ERROR] Communication device of robot 'sam' not properly defined!`
`[ERROR] Robot not properly defined!`
The simulator crashes after that.

This is how I instantiate (e.g.) the USBL in SAM's XML file, but the same happens with the other communication devices:
```xml
<comm name="USBL" type="usbl" device_id="9">
  <specs min_vertical_fov="0.0" max_vertical_fov="220.0" range="8000.0"/>
  <connect device_id="5" occlusion_test="false"/>
  <autoping rate="1.0"/>
  <noise range="0.05" horizontal_angle="0.2" vertical_angle="0.5"/>
  <resolution range="0.01" angle="0.1"/>
  <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
  <link name="Vehicle"/>
  <ros_publisher topic="/$(arg robot_name)/sim/usbl"/>
</comm>
```
It seems to work fine when I build stonefish_ros and Stonefish from the [original repos](https://github.com/patrykcieslak), but that seems to break other smarc-related services.

Running on **Ubuntu 18.04 with ROS Melodic**.

**Comment by nilsbore** [comment]
Hi Aldo! There's been some changes to upstream stonefish since we last updated our version. I think this commit probably covers the relevant changes: https://github.com/patrykcieslak/stonefish/commit/96afa6dd9a83e96ba7ae54870a68f1069291f91f . See if you can figure out what you need to change in order to revert to the old changes (check the scenario parser changes).

**Comment by aldoteran** [comment]
Thanks for the super quick response Nils!

The changes were in fact in that commit, they changed the way the FOV for the device is specified, just had to change
```xml
<specs min_vertical_fov="X.X" max_vertical_fov="X.X" range="8000.0"/>
```
to
```xml
<specs vertical_fov="X.X" horizontal_fov="X.X" range="8000.0"/>
```
and it worked like a charm. Thanks a lot!
